import { CampaignLaunchChecklist, CreatorReadinessBadge, ManualApprovalNotice, SafetyNotice, SectionHeader, StatusBadge, XpeXPageShell } from '../../components';
import { xpexPhase10PilotOperation } from '../../lib/pilot-operation';

const matrix = [
  ['Transformação', 'Antes/depois do quarto com projetor', 'Reels/TikTok'],
  ['Bastidor', 'Anderso testando parede, distância e beat', 'Shorts/Stories'],
  ['Prova social', 'Amigos reagindo à parede virando telão', 'Reels/Status'],
  ['Review curto', 'O que conferir antes de comprar', 'Shorts/TikTok'],
];

export default function AndersoPage() { const pilot = xpexPhase10PilotOperation; return <XpeXPageShell eyebrow="Criador piloto · Fase 10" title="Anderso" description="Perfil comercial do primeiro criador piloto para operação interna real controlada com produto de entretenimento/projetor."><SafetyNotice notice="Perfil piloto sem imagem real, sem coleta de dados sensíveis e sem publicação automática." /><ManualApprovalNotice /><section className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-7"><SectionHeader eyebrow="Perfil comercial" title={pilot.creator.role} description={pilot.creator.audience} /><div className="mt-5 flex flex-wrap gap-3">{pilot.creator.channels.map((channel) => <StatusBadge key={channel}>{channel}</StatusBadge>)}<StatusBadge>{pilot.creator.status}</StatusBadge></div><p className="mt-5 rounded-2xl bg-black/25 p-4 text-white/70">Tom de voz: {pilot.creator.tone}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{pilot.creator.contentTypes.map((item) => <CreatorReadinessBadge key={item} label={item} />)}</div></section><section className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-7"><SectionHeader eyebrow="Matriz de conteúdo" title="Projetor portátil / entretenimento" /><div className="mt-6 overflow-hidden rounded-3xl border border-white/10"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-white/10 text-white"><tr>{['Pilar','Ideia','Canal'].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{matrix.map((row) => <tr key={row[0]} className="border-t border-white/10 text-white/70">{row.map((cell) => <td key={cell} className="px-4 py-4">{cell}</td>)}</tr>)}</tbody></table></div></section><CampaignLaunchChecklist items={['Bio revisada', 'Link manual seguro', 'Roteiro aprovado', 'Criativo revisado', 'CTA sem promessa enganosa', 'Aprovação humana', 'Publicação manual']} /></XpeXPageShell>; }
