import Link from 'next/link';
import { CampaignLaunchChecklist, ManualApprovalNotice, OperationModeBadge, PilotOperationCard, SafetyNotice, SectionHeader, XpeXPageShell } from '../components';
import { xpexPhase10PilotOperation } from '../lib/pilot-operation';

export default function XpeXOperationPage() {
  const pilot = xpexPhase10PilotOperation;
  return <XpeXPageShell eyebrow="Fase 10 · Operação Real Controlada" title="Primeira operação interna real" description="Fluxo piloto com produto manual, campanha Seu quarto vira palco e criador Anderso, sem APIs externas, sem publicação automática e com aprovação humana antes de qualquer ação pública.">
    <SafetyNotice notice={pilot.principle} />
    <OperationModeBadge mode="local" availability="disabled" notice="Fase 10 roda como superfície interna de revisão: dados piloto reais, operação manual e integrações externas desligadas." />
    <ManualApprovalNotice />
    <section className="grid gap-5 lg:grid-cols-3"><PilotOperationCard title="Criador" value={pilot.creator.name} detail={`${pilot.creator.role}. ${pilot.creator.audience}`} status={pilot.creator.status} /><PilotOperationCard title="Produto" value={pilot.product.name} detail={pilot.product.positioning} status={pilot.product.status} /><PilotOperationCard title="Campanha" value={pilot.campaign.name} detail={pilot.campaign.angle} status={pilot.campaign.status} /></section>
    <section className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-7"><SectionHeader eyebrow="Fluxo completo" title="Produto → campanha → criador → criativo → link manual → lead → métrica" description="A Fase 10 valida o fluxo comercial ponta a ponta sem conectar Mercado Livre API, Dub, n8n, OpenAI, WhatsApp ou anúncios pagos." /><div className="mt-6 grid gap-3 md:grid-cols-7">{pilot.flow.map((step, index) => <div key={step} className="rounded-2xl border border-white/10 bg-black/25 p-4"><span className="text-xs font-black text-[#F5B301]">0{index + 1}</span><p className="mt-2 text-sm font-bold capitalize text-white/75">{step}</p></div>)}</div></section>
    <section className="grid gap-5 lg:grid-cols-2"><article className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-7"><SectionHeader eyebrow="Criativos" title="Briefs por canal" /><div className="mt-5 space-y-4">{pilot.creativeBriefs.map((brief) => <div key={brief.format} className="rounded-2xl border border-white/10 bg-black/25 p-4"><strong className="text-[#F5B301]">{brief.format}</strong><p className="mt-2 text-white/75">{brief.hook}</p><p className="mt-2 text-sm text-white/58">{brief.script15s}</p></div>)}</div></article><article className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-7"><SectionHeader eyebrow="Links" title="Plano manual sem encurtador" /><div className="mt-5 space-y-4">{pilot.manualLinkPlan.map((link) => <div key={link.channel} className="rounded-2xl border border-white/10 bg-black/25 p-4"><strong className="text-[#B8FFD0]">{link.channel}</strong><p className="mt-2 break-all text-sm text-white/65">{link.suggestedUtm}</p><p className="mt-2 text-xs text-white/50">{link.notes}</p></div>)}</div></article></section>
    <CampaignLaunchChecklist items={pilot.checklist} />
    <section className="rounded-[2rem] border border-[#F5B301]/25 bg-[#F5B301]/10 p-7"><SectionHeader eyebrow="Próxima ação" title="Revisar URL real do produto e aprovar roteiro antes de publicar manualmente" description="Depois da aprovação humana, registrar leads e métricas manualmente para preparar a Fase 11 de rastreamento avançado." /><div className="mt-5 flex flex-wrap gap-3"><Link className="rounded-full bg-[#F5B301] px-5 py-3 font-black text-[#071B33]" href="/xpex-commerce/creators/anderso">Perfil Anderso</Link><Link className="rounded-full border border-white/20 px-5 py-3 font-black text-white" href="/xpex-commerce/campaigns/seu-quarto-vira-palco">Brief da campanha</Link></div></section>
  </XpeXPageShell>;
}
