import Link from 'next/link';
import { ReactNode } from 'react';
import { xpexBrandTokens } from '@gitroom/frontend/app/xpex-brand-tokens';
import { getXpeXStorageModeDescription, getXpeXStorageModeLabel, type XpeXBackendAvailability, type XpeXStorageMode } from '../lib/storage-mode';
import type { DeployReadinessGroup, DeployReadinessItem, XpeXDeployEnvironment } from '../lib/deploy-readiness';

const tokens = xpexBrandTokens.colors;

export function XpeXPageShell({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: ReactNode }) {
  return <main className="min-h-screen overflow-hidden px-6 py-8 text-white md:px-10 lg:px-14" style={{ background: `radial-gradient(circle at top left, ${tokens.electricBlue}55, transparent 34rem), radial-gradient(circle at 78% 10%, ${tokens.gold}33, transparent 28rem), linear-gradient(135deg, ${tokens.darkBackground}, ${tokens.navy} 52%, #02040A)`, fontFamily: xpexBrandTokens.fontFamily }}><section className="mx-auto flex max-w-7xl flex-col gap-8"><header className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-8 shadow-2xl shadow-black/30 backdrop-blur md:p-10"><Link href="/xpex-commerce" className="text-sm font-bold text-[#8DB4FF]">← Dashboard XpeX</Link><p className="mt-8 text-sm font-bold uppercase tracking-[0.35em] text-[#F5B301]">{eyebrow}</p><h1 className="mt-4 max-w-5xl text-4xl font-black tracking-[-0.04em] md:text-6xl">{title}</h1><p className="mt-5 max-w-4xl text-lg leading-8 text-white/72">{description}</p></header>{children}</section></main>;
}


export function SafetyNotice({ mode = 'local', availability = 'disabled', notice }: { mode?: XpeXStorageMode; availability?: XpeXBackendAvailability; notice?: string }) {
  const label = getXpeXStorageModeLabel(mode);
  const description = notice || getXpeXStorageModeDescription(mode, availability);
  return <aside className="rounded-[2rem] border border-[#22C55E]/25 bg-[#22C55E]/10 p-5 text-sm leading-6 text-white/72"><strong className="text-[#B8FFD0]">{label} · Fase 12 · Links rastreáveis, UTMs e atribuição manual:</strong> {description} Encurtador externo, redirect público real, Mercado Livre, Dub, n8n, OpenAI, WhatsApp e anúncios pagos seguem desconectados.</aside>;
}

export function OperationModeBadge({ mode, availability, notice }: { mode: XpeXStorageMode; availability: XpeXBackendAvailability; notice: string }) {
  return <section className="rounded-[2rem] border border-[#8DB4FF]/25 bg-[#8DB4FF]/10 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold uppercase tracking-[0.28em] text-[#8DB4FF]">Status da operação</p><h2 className="mt-2 text-2xl font-black text-white">{getXpeXStorageModeLabel(mode)}</h2></div><StatusBadge>{availability}</StatusBadge></div><p className="mt-4 text-sm leading-6 text-white/70">{notice}</p><p className="mt-3 text-xs font-bold uppercase tracking-[0.18em] text-[#B8FFD0]">Backend controlado em homologação; integrações externas desligadas.</p></section>;
}

export function StatusBadge({ children }: { children: ReactNode }) { return <span className="rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-white/80">{children}</span>; }
export function SectionHeader({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) { return <div><p className="text-sm font-bold uppercase tracking-[0.28em] text-[#22C55E]">{eyebrow}</p><h2 className="mt-3 text-3xl font-black text-white">{title}</h2>{description ? <p className="mt-3 text-white/62">{description}</p> : null}</div>; }
export function MetricCard({ label, value, detail }: { label: string; value: string | number; detail: string }) { return <article className="rounded-3xl border border-white/10 bg-white/[0.06] p-5 shadow-2xl shadow-black/20 backdrop-blur"><p className="text-sm text-white/55">{label}</p><strong className="mt-3 block text-3xl font-black text-white">{value}</strong><p className="mt-2 text-sm leading-6 text-white/60">{detail}</p></article>; }
export function ModuleCard({ href, title, detail, cta }: { href: string; title: string; detail: string; cta: string }) { return <Link href={href} className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-6 transition hover:-translate-y-1 hover:border-[#F5B301]/45 hover:bg-white/[0.09]"><h3 className="text-2xl font-black text-white">{title}</h3><p className="mt-3 min-h-[4rem] text-sm leading-6 text-white/62">{detail}</p><span className="mt-5 inline-flex rounded-full bg-[#F5B301] px-4 py-2 text-sm font-black text-[#071B33]">{cta}</span></Link>; }
export function ProductCard({ product }: { product: { name: string; category: string; score: number; status: string; creatorFit: string; campaignAngle: string; ctaKeyword: string; notes: string } }) { return <article className="rounded-[2rem] border border-white/10 bg-[#081322]/85 p-6"><div className="flex items-start justify-between gap-4"><div><h3 className="text-2xl font-black">{product.name}</h3><p className="mt-1 text-sm text-white/55">{product.category}</p></div><StatusBadge>{product.status}</StatusBadge></div><p className="mt-4 text-4xl font-black text-[#F5B301]">{product.score}/10</p><p className="mt-4 text-sm leading-6 text-white/65">{product.creatorFit}</p><p className="mt-4 rounded-2xl bg-black/25 p-4 text-sm text-white/70">Ângulo: {product.campaignAngle} · CTA: {product.ctaKeyword}</p><p className="mt-4 text-sm leading-6 text-white/55">{product.notes}</p></article>; }
export function CampaignCard({ campaign }: { campaign: { name: string; product: string; creator: string; cta: string; score: number; status: string; briefing: string; channels: readonly string[] } }) { return <article className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-2xl font-black">{campaign.name}</h3><StatusBadge>{campaign.status}</StatusBadge></div><p className="mt-3 text-white/65">{campaign.product} · {campaign.creator} · Score {campaign.score}/10</p><p className="mt-4 rounded-2xl bg-black/25 p-4 font-bold text-white">CTA: {campaign.cta}</p><p className="mt-4 text-sm leading-6 text-white/62">{campaign.briefing}</p><div className="mt-5 flex flex-wrap gap-2">{campaign.channels.map((channel) => <StatusBadge key={channel}>{channel}</StatusBadge>)}</div></article>; }
export function LinkPlanCard({ link }: { link: { channel: string; slug: string; campaign: string; status: string } }) { return <article className="rounded-3xl border border-white/10 bg-[#081322]/85 p-5"><StatusBadge>{link.channel}</StatusBadge><h3 className="mt-4 text-xl font-black">{link.slug}</h3><p className="mt-2 text-sm text-white/60">{link.campaign}</p><p className="mt-4 text-sm text-[#B8FFD0]">{link.status}</p></article>; }


export function PilotOperationCard({ title, value, detail, status }: { title: string; value: string; detail: string; status: string }) { return <article className="rounded-[2rem] border border-[#F5B301]/25 bg-[#F5B301]/10 p-6"><p className="text-sm font-bold uppercase tracking-[0.25em] text-[#F5B301]">{title}</p><h3 className="mt-3 text-2xl font-black text-white">{value}</h3><p className="mt-3 text-sm leading-6 text-white/68">{detail}</p><div className="mt-5"><StatusBadge>{status}</StatusBadge></div></article>; }
export function CreatorReadinessBadge({ label, ready = true }: { label: string; ready?: boolean }) { return <div className={`rounded-2xl border p-4 text-sm font-bold ${ready ? 'border-[#22C55E]/25 bg-[#22C55E]/10 text-[#B8FFD0]' : 'border-amber-300/25 bg-amber-300/10 text-amber-100'}`}>{ready ? '✓' : '•'} {label}</div>; }
export function CampaignLaunchChecklist({ items }: { items: readonly string[] }) { return <section className="rounded-[2rem] border border-[#22C55E]/25 bg-[#22C55E]/10 p-7"><SectionHeader eyebrow="Checklist" title="Aprovação humana antes da publicação" description="Nenhum post, anúncio, mensagem ou link é publicado automaticamente." /><div className="mt-6 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{items.map((item) => <CreatorReadinessBadge key={item} label={item} />)}</div></section>; }
export function ManualApprovalNotice() { return <aside className="rounded-[2rem] border border-amber-300/30 bg-amber-300/10 p-5 text-sm leading-6 text-amber-50"><strong>Aprovação manual obrigatória:</strong> revisar produto, URL, roteiro, CTA, compliance e canal antes de qualquer publicação feita por humano. Mercado Livre API, Dub, n8n, OpenAI, WhatsApp e anúncios pagos continuam desligados.</aside>; }

export function ImportStatusBadge({ status }: { status: 'ready' | 'warning' | 'blocked' | string }) {
  const color = status === 'ready' ? 'border-[#22C55E]/40 bg-[#22C55E]/15 text-[#B8FFD0]' : status === 'blocked' ? 'border-red-300/40 bg-red-500/15 text-red-100' : 'border-amber-300/40 bg-amber-300/15 text-amber-100';
  return <span className={`rounded-full border px-3 py-1 text-xs font-black uppercase tracking-[0.18em] ${color}`}>{status}</span>;
}

export function CrudReadinessBadge({ ready, label }: { ready: boolean; label: string }) {
  return <div className={`rounded-2xl border p-4 text-sm font-bold ${ready ? 'border-[#22C55E]/25 bg-[#22C55E]/10 text-[#B8FFD0]' : 'border-amber-300/25 bg-amber-300/10 text-amber-100'}`}>{ready ? '✓' : '•'} {label}</div>;
}

export function ImportPlanCard({ title, value, detail }: { title: string; value: string | number; detail: string }) {
  return <article className="rounded-3xl border border-white/10 bg-black/20 p-5"><p className="text-sm text-white/55">{title}</p><strong className="mt-2 block text-3xl font-black text-white">{value}</strong><p className="mt-2 text-sm leading-6 text-white/60">{detail}</p></article>;
}

export function ManualTrackingNotice() { return <aside className="rounded-[2rem] border border-amber-300/30 bg-amber-300/10 p-5 text-sm leading-6 text-amber-50"><strong>Rastreamento manual Fase 11:</strong> visualizações, cliques, leads, mensagens e vendas são digitados por operador humano. Não há scraping, publicação automática, pixel, encurtador, WhatsApp API ou leitura automática de redes sociais.</aside>; }

export function ChannelPerformanceTable({ channels }: { channels: { channel: string; views: number; clicks: number; leads: number; messages: number; sales: number; ctr: number; leadRate: number; conversionRate: number; estimatedCommission: number }[] }) { return <div className="overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.055]"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-white/10 text-white/70"><tr>{['Canal','Views','Cliques','Leads','Mensagens','Vendas','CTR','Lead rate','Conversão','Comissão'].map((h) => <th key={h} className="px-4 py-3 font-black">{h}</th>)}</tr></thead><tbody>{channels.map((row) => <tr key={row.channel} className="border-t border-white/10 text-white/70"><td className="px-4 py-3 font-bold text-white">{row.channel}</td><td className="px-4 py-3">{row.views}</td><td className="px-4 py-3">{row.clicks}</td><td className="px-4 py-3">{row.leads}</td><td className="px-4 py-3">{row.messages}</td><td className="px-4 py-3">{row.sales}</td><td className="px-4 py-3">{row.ctr}%</td><td className="px-4 py-3">{row.leadRate}%</td><td className="px-4 py-3">{row.conversionRate}%</td><td className="px-4 py-3">R$ {row.estimatedCommission.toFixed(2)}</td></tr>)}</tbody></table></div>; }

export function CreativeRankingCard({ creative, index }: { creative: { creative: string; channel: string; views: number; clicks: number; leads: number; messages: number; sales: number; score: number }; index: number }) { return <article className="rounded-3xl border border-white/10 bg-[#081322]/85 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black text-[#F5B301]">#{index + 1} · {creative.channel}</p><h3 className="mt-2 text-xl font-black text-white">{creative.creative}</h3></div><StatusBadge>score {creative.score}</StatusBadge></div><p className="mt-4 text-sm text-white/62">{creative.views} views · {creative.clicks} cliques · {creative.leads} leads · {creative.messages} mensagens · {creative.sales} vendas manuais</p></article>; }

export function FunnelSnapshot({ steps }: { steps: { label: string; value: string | number }[] }) { return <div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6">{steps.map((step, index) => <article key={step.label} className="rounded-3xl border border-[#22C55E]/20 bg-[#22C55E]/10 p-5"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#B8FFD0]">0{index + 1}</p><strong className="mt-3 block text-3xl font-black text-white">{step.value}</strong><p className="mt-2 text-sm text-white/65">{step.label}</p></article>)}</div>; }

export function ContentCalendarCard({ item }: { item: { day: string; channel: string; format: string; hook: string; cta: string; status: string } }) { return <article className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black uppercase tracking-[0.2em] text-[#8DB4FF]">{item.day}</p><h3 className="mt-2 text-xl font-black text-white">{item.channel} · {item.format}</h3></div><StatusBadge>{item.status}</StatusBadge></div><p className="mt-4 text-sm leading-6 text-white/68">Hook: {item.hook}</p><p className="mt-3 rounded-2xl bg-black/25 p-4 text-sm font-bold text-white/75">CTA: {item.cta}</p></article>; }

export function LinkRiskBadge({ risk }: { risk: string }) { const color = risk === 'safe' ? 'border-[#22C55E]/35 bg-[#22C55E]/15 text-[#B8FFD0]' : risk === 'blocked' ? 'border-red-300/35 bg-red-500/15 text-red-100' : 'border-amber-300/35 bg-amber-300/15 text-amber-100'; return <span className={`rounded-full border px-3 py-1 text-xs font-black uppercase tracking-[0.16em] ${color}`}>{risk}</span>; }
export function UtmPreviewBox({ url }: { url: string }) { return <pre className="whitespace-pre-wrap break-all rounded-3xl border border-[#8DB4FF]/20 bg-black/30 p-5 text-sm leading-6 text-[#B8FFD0]">{url || 'Informe uma URL http/https válida para gerar UTMs localmente.'}</pre>; }
export function TrackedLinkCard({ link }: { link: { slug: string; campaign: string; creator: string; channel: string; creative: string; status: string; utmUrl: string; manualClicks: number; manualLeads: number; manualSales: number; estimatedCommission: number; riskStatus: string } }) { return <article className="rounded-[2rem] border border-white/10 bg-[#081322]/85 p-6"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-black text-white">{link.slug}</h3><p className="mt-2 text-sm text-white/60">{link.campaign} · {link.creator} · {link.channel}</p></div><LinkRiskBadge risk={link.riskStatus} /></div><p className="mt-4 text-sm text-white/65">Criativo: {link.creative}</p><p className="mt-3 break-all text-xs text-white/50">{link.utmUrl}</p><p className="mt-4 text-sm text-[#B8FFD0]">{link.status} · {link.manualClicks} cliques · {link.manualLeads} leads · {link.manualSales} vendas · R$ {link.estimatedCommission.toFixed(2)}</p></article>; }
export function LinkPerformanceRanking({ rows }: { rows: { linkId: string; slug: string; clicks: number; leads: number; sales: number; estimatedCommission: number; leadRate: number; salesRate: number; score: number }[] }) { return <div className="overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.055]"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-white/10 text-white/70"><tr>{['Link','Cliques','Leads','Vendas','Lead rate','Sales rate','Comissão','Score'].map((h) => <th key={h} className="px-4 py-3 font-black">{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.linkId} className="border-t border-white/10 text-white/68"><td className="px-4 py-3 font-bold text-white">{row.slug}</td><td className="px-4 py-3">{row.clicks}</td><td className="px-4 py-3">{row.leads}</td><td className="px-4 py-3">{row.sales}</td><td className="px-4 py-3">{row.leadRate}%</td><td className="px-4 py-3">{row.salesRate}%</td><td className="px-4 py-3">R$ {row.estimatedCommission.toFixed(2)}</td><td className="px-4 py-3">{row.score}</td></tr>)}</tbody></table></div>; }
export function LinkAttributionTable({ rows }: { rows: { id: string; linkId: string; leadId?: string; kind: string; status: string; reportedValue: number; estimatedCommission: number; date: string }[] }) { return <div className="overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.055]"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-white/10 text-white/70"><tr>{['Tipo','Link','Lead','Status','Valor','Comissão','Data'].map((h) => <th key={h} className="px-4 py-3 font-black">{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-white/10 text-white/68"><td className="px-4 py-3">{row.kind}</td><td className="px-4 py-3">{row.linkId}</td><td className="px-4 py-3">{row.leadId || '—'}</td><td className="px-4 py-3">{row.status}</td><td className="px-4 py-3">R$ {row.reportedValue.toFixed(2)}</td><td className="px-4 py-3">R$ {row.estimatedCommission.toFixed(2)}</td><td className="px-4 py-3">{row.date}</td></tr>)}</tbody></table></div>; }


export function DeployReadinessCard({ item }: { item: DeployReadinessItem }) {
  const color = item.status === 'ready' ? 'border-[#22C55E]/30 bg-[#22C55E]/10 text-[#B8FFD0]' : item.status === 'blocked' ? 'border-red-300/35 bg-red-500/15 text-red-100' : 'border-amber-300/35 bg-amber-300/15 text-amber-100';
  return <article className={`rounded-3xl border p-5 ${color}`}><div className="flex flex-wrap items-start justify-between gap-3"><h3 className="text-lg font-black text-white">{item.label}</h3><span className="rounded-full border border-white/15 bg-black/20 px-3 py-1 text-xs font-black uppercase tracking-[0.16em]">{item.status}</span></div><p className="mt-3 text-sm leading-6 text-white/68">{item.detail}</p><p className="mt-4 text-xs font-bold uppercase tracking-[0.16em] text-white/55">{item.target} · {item.owner}</p></article>;
}

export function DeployReadinessGroupPanel({ group }: { group: DeployReadinessGroup }) {
  return <section className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-7"><SectionHeader eyebrow="Deploy checklist" title={group.title} description={group.description} /><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{group.items.map((item) => <DeployReadinessCard key={item.id} item={item} />)}</div></section>;
}

export function DeployEnvironmentMatrix({ environments }: { environments: XpeXDeployEnvironment[] }) {
  return <div className="grid gap-4 lg:grid-cols-2">{environments.map((environment) => <article key={environment.id} className="rounded-[2rem] border border-[#8DB4FF]/20 bg-[#8DB4FF]/10 p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#8DB4FF]">{environment.id}</p><h3 className="mt-2 text-2xl font-black text-white">{environment.label}</h3></div><StatusBadge>safe</StatusBadge></div><p className="mt-4 text-sm leading-6 text-white/68">{environment.purpose}</p><p className="mt-4 rounded-2xl bg-black/25 p-4 text-sm font-bold text-white/75">{environment.recommendedState}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-[#B8FFD0]">Placeholders permitidos</p><ul className="mt-2 space-y-2 text-xs text-white/62">{environment.allowedEnv.map((item) => <li key={item}>• {item}</li>)}</ul></div><div><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-100">Ações bloqueadas</p><ul className="mt-2 space-y-2 text-xs text-white/62">{environment.blockedActions.map((item) => <li key={item}>• {item}</li>)}</ul></div></div></article>)}</div>;
}

export function DeployCommandBox({ title, commands }: { title: string; commands: string[] }) {
  return <article className="rounded-[2rem] border border-white/10 bg-black/25 p-6"><h3 className="text-xl font-black text-white">{title}</h3><pre className="mt-4 overflow-auto whitespace-pre-wrap rounded-2xl border border-white/10 bg-black/35 p-4 text-sm leading-7 text-[#B8FFD0]">{commands.join('\n')}</pre></article>;
}

export function DeployGuardrailList({ items }: { items: string[] }) {
  return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <div key={item} className="rounded-2xl border border-[#22C55E]/25 bg-[#22C55E]/10 p-4 text-sm font-bold text-[#B8FFD0]">✓ {item}</div>)}</div>;
}
