import Link from 'next/link';
import { ReactNode } from 'react';
import { xpexBrandTokens } from '@gitroom/frontend/app/xpex-brand-tokens';

const tokens = xpexBrandTokens.colors;

export function XpeXPageShell({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: ReactNode }) {
  return <main className="min-h-screen overflow-hidden px-6 py-8 text-white md:px-10 lg:px-14" style={{ background: `radial-gradient(circle at top left, ${tokens.electricBlue}55, transparent 34rem), radial-gradient(circle at 78% 10%, ${tokens.gold}33, transparent 28rem), linear-gradient(135deg, ${tokens.darkBackground}, ${tokens.navy} 52%, #02040A)`, fontFamily: xpexBrandTokens.fontFamily }}><section className="mx-auto flex max-w-7xl flex-col gap-8"><header className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-8 shadow-2xl shadow-black/30 backdrop-blur md:p-10"><Link href="/xpex-commerce" className="text-sm font-bold text-[#8DB4FF]">← Dashboard XpeX</Link><p className="mt-8 text-sm font-bold uppercase tracking-[0.35em] text-[#F5B301]">{eyebrow}</p><h1 className="mt-4 max-w-5xl text-4xl font-black tracking-[-0.04em] md:text-6xl">{title}</h1><p className="mt-5 max-w-4xl text-lg leading-8 text-white/72">{description}</p></header>{children}</section></main>;
}

export function StatusBadge({ children }: { children: ReactNode }) { return <span className="rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-white/80">{children}</span>; }
export function SectionHeader({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) { return <div><p className="text-sm font-bold uppercase tracking-[0.28em] text-[#22C55E]">{eyebrow}</p><h2 className="mt-3 text-3xl font-black text-white">{title}</h2>{description ? <p className="mt-3 text-white/62">{description}</p> : null}</div>; }
export function MetricCard({ label, value, detail }: { label: string; value: string | number; detail: string }) { return <article className="rounded-3xl border border-white/10 bg-white/[0.06] p-5 shadow-2xl shadow-black/20 backdrop-blur"><p className="text-sm text-white/55">{label}</p><strong className="mt-3 block text-3xl font-black text-white">{value}</strong><p className="mt-2 text-sm leading-6 text-white/60">{detail}</p></article>; }
export function ModuleCard({ href, title, detail, cta }: { href: string; title: string; detail: string; cta: string }) { return <Link href={href} className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-6 transition hover:-translate-y-1 hover:border-[#F5B301]/45 hover:bg-white/[0.09]"><h3 className="text-2xl font-black text-white">{title}</h3><p className="mt-3 min-h-[4rem] text-sm leading-6 text-white/62">{detail}</p><span className="mt-5 inline-flex rounded-full bg-[#F5B301] px-4 py-2 text-sm font-black text-[#071B33]">{cta}</span></Link>; }
export function ProductCard({ product }: { product: { name: string; category: string; score: number; status: string; creatorFit: string; campaignAngle: string; ctaKeyword: string; notes: string } }) { return <article className="rounded-[2rem] border border-white/10 bg-[#081322]/85 p-6"><div className="flex items-start justify-between gap-4"><div><h3 className="text-2xl font-black">{product.name}</h3><p className="mt-1 text-sm text-white/55">{product.category}</p></div><StatusBadge>{product.status}</StatusBadge></div><p className="mt-4 text-4xl font-black text-[#F5B301]">{product.score}/10</p><p className="mt-4 text-sm leading-6 text-white/65">{product.creatorFit}</p><p className="mt-4 rounded-2xl bg-black/25 p-4 text-sm text-white/70">Ângulo: {product.campaignAngle} · CTA: {product.ctaKeyword}</p><p className="mt-4 text-sm leading-6 text-white/55">{product.notes}</p></article>; }
export function CampaignCard({ campaign }: { campaign: { name: string; product: string; creator: string; cta: string; score: number; status: string; briefing: string; channels: readonly string[] } }) { return <article className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-2xl font-black">{campaign.name}</h3><StatusBadge>{campaign.status}</StatusBadge></div><p className="mt-3 text-white/65">{campaign.product} · {campaign.creator} · Score {campaign.score}/10</p><p className="mt-4 rounded-2xl bg-black/25 p-4 font-bold text-white">CTA: {campaign.cta}</p><p className="mt-4 text-sm leading-6 text-white/62">{campaign.briefing}</p><div className="mt-5 flex flex-wrap gap-2">{campaign.channels.map((channel) => <StatusBadge key={channel}>{channel}</StatusBadge>)}</div></article>; }
export function LinkPlanCard({ link }: { link: { channel: string; slug: string; campaign: string; status: string } }) { return <article className="rounded-3xl border border-white/10 bg-[#081322]/85 p-5"><StatusBadge>{link.channel}</StatusBadge><h3 className="mt-4 text-xl font-black">{link.slug}</h3><p className="mt-2 text-sm text-white/60">{link.campaign}</p><p className="mt-4 text-sm text-[#B8FFD0]">{link.status}</p></article>; }
