'use client';

import { FormEvent, useState } from 'react';
import { SectionHeader, StatusBadge } from '.';
import type { XpeXCommerceChannel, XpeXCommerceStatus } from '../lib/types';
import { useXpeXCommerceStore } from '../lib/use-xpex-commerce-store';

const inputClass = 'mt-2 w-full rounded-2xl border border-white/10 bg-black/25 px-4 py-3 text-sm text-white outline-none placeholder:text-white/30 focus:border-[#F5B301]/70';
const labelClass = 'text-sm font-bold text-white/70';
const statuses: XpeXCommerceStatus[] = ['Em análise', 'Aprovado', 'Em campanha', 'Vencedor', 'Pausado', 'Descartado'];
const leadStatuses: XpeXCommerceStatus[] = ['Novo', 'Link enviado', 'Interessado', 'Comprou', 'Follow-up', 'Não respondeu', 'Descartado'];
const channels: XpeXCommerceChannel[] = ['Instagram', 'TikTok', 'WhatsApp', 'Manual', 'Outro'];
const splitChannels = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean) as XpeXCommerceChannel[];

function SubmitButton({ children }: { children: string }) { return <button type="submit" className="rounded-full bg-[#F5B301] px-5 py-3 text-sm font-black text-[#071B33] transition hover:brightness-110">{children}</button>; }

export function ProductForm() {
  const { addProduct } = useXpeXCommerceStore();
  const [saved, setSaved] = useState(false);
  function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); addProduct({ name: String(form.get('name') || 'Produto sem nome'), category: String(form.get('category') || 'Sem categoria'), mercadoLivreUrl: String(form.get('mercadoLivreUrl') || ''), audienceFit: String(form.get('audienceFit') || ''), creator: String(form.get('creator') || 'Anderso'), creatorFit: `Fit local para ${String(form.get('creator') || 'Anderso')}`, campaignAngle: String(form.get('campaignAngle') || ''), ctaKeyword: String(form.get('ctaKeyword') || ''), score: Number(form.get('score') || 7), status: String(form.get('status') || 'Em análise') as XpeXCommerceStatus, notes: String(form.get('notes') || '') }); event.currentTarget.reset(); setSaved(true); }
  return <form onSubmit={onSubmit} className="rounded-[2rem] border border-[#F5B301]/25 bg-[#F5B301]/10 p-7"><SectionHeader eyebrow="Cadastro local" title="Novo produto manual" description="Salva somente no localStorage deste navegador." /><div className="mt-6 grid gap-4 md:grid-cols-2">{[['name','Nome do produto'],['category','Categoria'],['mercadoLivreUrl','Link Mercado Livre opcional'],['audienceFit','Público'],['creator','Criador'],['campaignAngle','Ângulo/campanha'],['ctaKeyword','CTA'],['score','Score']].map(([name,label]) => <label key={name} className={labelClass}>{label}<input name={name} type={name === 'score' ? 'number' : 'text'} min="0" max="10" step="0.1" className={inputClass} /></label>)}<label className={labelClass}>Status<select name="status" className={inputClass}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><label className={`${labelClass} md:col-span-2`}>Observações<textarea name="notes" className={inputClass} rows={3} /></label></div><div className="mt-6 flex items-center gap-3"><SubmitButton>Salvar produto local</SubmitButton>{saved ? <StatusBadge>Salvo localmente</StatusBadge> : null}</div></form>;
}

export function CampaignForm() { const { addCampaign } = useXpeXCommerceStore(); return <SimpleForm title="Nova campanha manual" fields={['name:Nome', 'product:Produto', 'creator:Criador', 'slogan:Slogan', 'cta:CTA', 'channels:Canais separados por vírgula', 'expectedMetric:Métrica esperada', 'briefing:Briefing']} onSubmit={(form) => addCampaign({ name: form.name, product: form.product, creator: form.creator || 'Anderso', slogan: form.slogan, cta: form.cta, channels: splitChannels(form.channels || 'Instagram'), status: 'Planejado', expectedMetric: form.expectedMetric, score: 7, briefing: form.briefing })} />; }
export function LinkPlanForm() { const { addLinkPlan } = useXpeXCommerceStore(); return <SimpleForm title="Novo slug planejado" fields={['campaign:Campanha', 'product:Produto', 'creator:Criador', 'channel:Canal', 'slug:Slug planejado', 'destinationUrl:Link destino opcional']} onSubmit={(form) => addLinkPlan({ campaign: form.campaign, product: form.product, creator: form.creator || 'Anderso', channel: (form.channel || 'Instagram') as XpeXCommerceChannel, slug: form.slug, destinationUrl: form.destinationUrl, status: 'Planejado', notes: 'Slug local; sem redirect real.' })} />; }
export function LeadForm() { const { addLead } = useXpeXCommerceStore(); return <SimpleForm title="Novo lead/CRM local" fields={['name:Nome', 'channel:Canal', 'interestedProduct:Produto de interesse', 'campaign:Campanha', 'creator:Criador', 'status:Status', 'observation:Observação']} onSubmit={(form) => addLead({ name: form.name, channel: (form.channel || 'Instagram') as XpeXCommerceChannel, interestedProduct: form.interestedProduct, campaign: form.campaign, creator: form.creator || 'Anderso', status: (form.status || 'Novo') as XpeXCommerceStatus, observation: form.observation })} />; }
export function CreativeBriefForm() { const { addCreativeBrief } = useXpeXCommerceStore(); return <SimpleForm title="Criativo manual local" fields={['campaign:Campanha', 'product:Produto', 'creator:Criador', 'hook:Hook', 'slogan:Slogan', 'caption:Legenda', 'shortScript:Roteiro curto', 'whatsappText:Texto WhatsApp']} onSubmit={(form) => addCreativeBrief({ campaign: form.campaign, product: form.product, creator: form.creator || 'Anderso', hook: form.hook, slogan: form.slogan, caption: form.caption, shortScript: form.shortScript, whatsappText: form.whatsappText, status: 'Planejado' })} />; }

function SimpleForm({ title, fields, onSubmit }: { title: string; fields: string[]; onSubmit: (values: Record<string, string>) => void }) { const [saved, setSaved] = useState(false); return <form onSubmit={(event) => { event.preventDefault(); const formData = new FormData(event.currentTarget); const data: Record<string, string> = {}; fields.forEach((field) => { const [name] = field.split(':'); data[name] = String(formData.get(name) || ''); }); onSubmit(data); event.currentTarget.reset(); setSaved(true); }} className="rounded-[2rem] border border-[#F5B301]/25 bg-[#F5B301]/10 p-7"><SectionHeader eyebrow="Operação local" title={title} description="Nenhum envio para servidor; persistência apenas no navegador." /><div className="mt-6 grid gap-4 md:grid-cols-2">{fields.map((field) => { const [name, label] = field.split(':'); const isStatus = name === 'status'; const isChannel = name === 'channel'; return <label key={name} className={labelClass}>{label}{isStatus ? <select name={name} className={inputClass}>{leadStatuses.map((status) => <option key={status}>{status}</option>)}</select> : isChannel ? <select name={name} className={inputClass}>{channels.map((channel) => <option key={channel}>{channel}</option>)}</select> : <input name={name} className={inputClass} />}</label>; })}</div><div className="mt-6 flex items-center gap-3"><SubmitButton>Salvar localmente</SubmitButton>{saved ? <StatusBadge>Salvo localmente</StatusBadge> : null}</div></form>; }

export function ExportJsonPanel() { const { exportJson, resetDemoData } = useXpeXCommerceStore(); const [json, setJson] = useState(''); return <section className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-7"><SectionHeader eyebrow="Exportação" title="JSON da operação local" description="Copia o estado atual salvo neste navegador para revisão manual." /><div className="mt-5 flex flex-wrap gap-3"><button onClick={() => setJson(exportJson())} className="rounded-full bg-[#22C55E] px-5 py-3 text-sm font-black text-[#071B33]">Gerar JSON</button><button onClick={() => { resetDemoData(); setJson(''); }} className="rounded-full border border-white/15 px-5 py-3 text-sm font-bold text-white/80">Resetar demo</button></div>{json ? <pre className="mt-5 max-h-80 overflow-auto rounded-2xl bg-black/40 p-4 text-xs text-white/70">{json}</pre> : null}</section>; }
