'use client';

import { FormEvent, useState } from 'react';
import { ManualTrackingNotice, SectionHeader, StatusBadge, XpeXPageShell, SafetyNotice } from '../components';
import { useXpeXCommerceStore } from '../lib/use-xpex-commerce-store';
import type { XpeXCommerceChannel } from '../lib/types';

const inputClass = 'mt-2 w-full rounded-2xl border border-white/10 bg-black/25 px-4 py-3 text-sm text-white outline-none focus:border-[#F5B301]/70';
const channels: XpeXCommerceChannel[] = ['Instagram', 'TikTok', 'YouTube Shorts', 'WhatsApp Status'];

export default function XpeXTrackingPage() {
  const { state, mode, backendAvailability, operationNotice, addManualMetric } = useXpeXCommerceStore();
  const [error, setError] = useState(''); const [saved, setSaved] = useState(false);
  function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const numberFields = ['views','estimatedClicks','leads','messages','manualSales']; const parsed = Object.fromEntries(numberFields.map((field) => [field, Number(form.get(field) || 0)])); if (Object.values(parsed).some((value) => Number.isNaN(value) || value < 0)) { setError('Campos numéricos devem ser zero ou positivos.'); return; } addManualMetric({ campaign: 'Seu quarto vira palco', channel: String(form.get('channel') || 'Instagram') as XpeXCommerceChannel, creative: String(form.get('creative') || 'Criativo manual'), date: String(form.get('date') || new Date().toISOString().slice(0, 10)), views: parsed.views, estimatedClicks: parsed.estimatedClicks, leads: parsed.leads, messages: parsed.messages, manualSales: parsed.manualSales, notes: String(form.get('notes') || '') }); event.currentTarget.reset(); setError(''); setSaved(true); }
  return <XpeXPageShell eyebrow="Phase 11 · Tracking" title="Rastreamento Manual da Campanha" description="Registro seguro de métricas do piloto, com revisão humana e persistência local/localStorage quando backend não estiver habilitado."><SafetyNotice mode={mode} availability={backendAvailability} notice={operationNotice} /><ManualTrackingNotice /><form onSubmit={onSubmit} className="rounded-[2rem] border border-[#F5B301]/25 bg-[#F5B301]/10 p-7"><SectionHeader eyebrow="Registro manual" title="Adicionar métrica" description="Não informe CPF, documento, endereço, senha, token ou dado sensível." /><div className="mt-6 grid gap-4 md:grid-cols-2"><label>Canal<select name="channel" className={inputClass}>{channels.map((c) => <option key={c}>{c}</option>)}</select></label><label>Criativo<input name="creative" className={inputClass} placeholder="Hook ou nome do criativo" /></label><label>Data<input type="date" name="date" className={inputClass} /></label>{[['views','Visualizações'],['estimatedClicks','Cliques estimados'],['leads','Leads'],['messages','Mensagens recebidas'],['manualSales','Vendas informadas']].map(([name,label]) => <label key={name}>{label}<input name={name} type="number" min="0" className={inputClass} /></label>)}<label className="md:col-span-2">Observações<textarea name="notes" rows={3} className={inputClass} /></label></div><div className="mt-6 flex gap-3"><button className="rounded-full bg-[#F5B301] px-5 py-3 font-black text-[#071B33]">Salvar métrica manual</button>{saved ? <StatusBadge>Salvo localmente</StatusBadge> : null}{error ? <StatusBadge>{error}</StatusBadge> : null}</div></form><section className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-7"><SectionHeader eyebrow="Histórico" title="Registros manuais" description="Dados preservados; nenhum apagamento automático." /><div className="mt-6 grid gap-4 lg:grid-cols-2">{(state.manualMetrics || []).map((metric) => <article key={metric.id} className="rounded-3xl border border-white/10 bg-black/20 p-5"><StatusBadge>{metric.channel}</StatusBadge><h3 className="mt-3 text-xl font-black">{metric.creative}</h3><p className="mt-3 text-sm text-white/65">{metric.views} views · {metric.estimatedClicks} cliques · {metric.leads} leads · {metric.messages} mensagens · {metric.manualSales} vendas</p><p className="mt-3 text-xs text-white/45">{metric.date} · {metric.notes}</p></article>)}</div></section></XpeXPageShell>;
}
