'use client';

import { useMemo, useState } from 'react';
import { OperationModeBadge, SafetyNotice, SectionHeader, TrackedLinkCard, XpeXPageShell } from '../components';
import { buildTrackedLinkDisplayMetrics, buildUtmUrl, generateSafeSlug, sanitizeDestinationUrl } from '../lib/link-attribution';
import { useXpeXCommerceStore } from '../lib/use-xpex-commerce-store';
import type { LinkStatus, XpeXCommerceChannel } from '../lib/types';

const statuses: LinkStatus[] = ['rascunho', 'aprovado', 'publicado manualmente', 'pausado', 'arquivado'];
export default function XpeXLinksPage() {
  const { state, mode, backendAvailability, operationNotice, addTrackedLink, updateTrackedLinkStatus } = useXpeXCommerceStore();
  const [destinationUrl, setDestinationUrl] = useState('https://example.com/projetor-portatil');
  const [channel, setChannel] = useState<XpeXCommerceChannel>('Instagram');
  const [creative, setCreative] = useState('Seu quarto parece normal até isso ligar.');
  const risk = sanitizeDestinationUrl(destinationUrl);
  const utm = useMemo(() => ({ source: channel.toLowerCase().replace(/\s+/g, '-'), medium: channel === 'WhatsApp Status' ? 'status' : 'social', campaign: 'seu-quarto-vira-palco', content: creative }), [channel, creative]);
  const slug = generateSafeSlug({ campaign: 'Seu quarto vira palco', creator: 'Anderso', channel, creative });
  const utmUrl = buildUtmUrl(destinationUrl, utm);
  return <XpeXPageShell eyebrow="Fase 12 · Links" title="Painel de Links Rastreáveis" description="Crie e acompanhe links com UTMs locais, slugs planejados e métricas manuais atribuídas; sem redirect público real e sem Dub."><SafetyNotice mode={mode} availability={backendAvailability} notice={operationNotice} /><OperationModeBadge mode={mode} availability={backendAvailability} notice={operationNotice} /><section className="rounded-[2rem] border border-[#F5B301]/25 bg-[#F5B301]/10 p-7"><SectionHeader eyebrow="Novo link manual" title="Construtor rápido de link rastreável" description="Destino original http/https, campanha Anderso e UTMs geradas localmente." /><div className="mt-6 grid gap-4 lg:grid-cols-4"><input className="rounded-2xl border border-white/10 bg-black/30 p-4 text-white lg:col-span-2" value={destinationUrl} onChange={(e) => setDestinationUrl(e.target.value)} /><select className="rounded-2xl border border-white/10 bg-black/30 p-4 text-white" value={channel} onChange={(e) => setChannel(e.target.value as XpeXCommerceChannel)}>{['Instagram','TikTok','YouTube Shorts','WhatsApp Status'].map((item) => <option key={item}>{item}</option>)}</select><input className="rounded-2xl border border-white/10 bg-black/30 p-4 text-white" value={creative} onChange={(e) => setCreative(e.target.value)} /></div><p className="mt-4 break-all text-sm text-white/65">Slug planejado: <strong>{slug}</strong><br />UTM: {utmUrl || risk.reason}</p><button className="mt-5 rounded-full bg-[#F5B301] px-5 py-3 font-black text-[#071B33] disabled:opacity-50" disabled={!risk.ok} onClick={() => addTrackedLink({ campaign: 'Seu quarto vira palco', product: 'Projetor portátil', creator: 'Anderso', channel, creative, destinationUrl: risk.value, utmUrl, slug, utm, status: 'rascunho', riskStatus: risk.risk, manualClicks: 0, manualLeads: 0, manualSales: 0, manualRevenue: 0, estimatedCommission: 0, notes: 'Criado manualmente na Fase 12.' })}>Salvar link rastreável</button></section><section className="grid gap-5 lg:grid-cols-2">{(state.trackedLinks || []).map((link) => { const displayMetrics = buildTrackedLinkDisplayMetrics(link, state.linkAttributions || []); return <div key={link.id}><TrackedLinkCard link={{ ...link, ...displayMetrics }} /><select className="mt-3 w-full rounded-2xl border border-white/10 bg-black/40 p-3 text-white" value={link.status} onChange={(e) => updateTrackedLinkStatus(link.id, e.target.value as LinkStatus)}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></div>; })}</section><section className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-7"><SectionHeader eyebrow="Limites" title="Preparação segura para encurtamento controlado" description="Nenhum redirect público real, encurtador externo, API social, OpenAI, n8n, WhatsApp ou Mercado Livre API foi conectado." /></section></XpeXPageShell>;
}
